### ISSUE TITLE
errors occured  when put the model into vits-fast-fine-tuning codes

### ISSUE THREAD

**Issue by cytheria43** [kdrkdrkdr/JK-VITS#2]
when I use your pretrained korean model to instead the models of  [CJE] languages ,errors occurred like the below pic shows.
I wonder its possible to  use it to train for my korean dataset?
looking forward to your reply,thanks!
![1710080234842](https://github.com/kdrkdrkdr/JK-VITS/assets/41312465/ca858101-06d3-4e8c-bc76-b16ea1587d27)

**Comment by kdrkdrkdr** [comment]
Vits model and mb-istft-vits model are not same.
So, You cannot load this pretrained model in vits-fast-fine-tuning
